name : basic
on : [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build
      - run: cmake -S . -B build && cmake --build build
      - run: ./main 4 6