name : basic
on : [push]
jobs: 

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build
      - run: cmake -S . -B build && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/main
            build/tests
            build/bench

  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests
      - run: ./tests

  benchmark:
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x bench && ./bench
  
  main:
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 5 6

  documentation:
    needs: [build, tests]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        contents: read
        pages: write
        id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install doxygen && doxygen --version
      - run: sudo apt install graphviz
      - run: doxygen -g Doxyfile
      - uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .
    
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4